[package]
name = "cboot"
version = "0.1.0"
authors = ["Adam Jones"]
edition = "2021"

[dependencies]
rlibc = "1.0"
x86_64 = "0.14.10"
raw-cpuid = "11.0.1"

[profile.dev]
opt-level = 'z'

[profile.release]
opt-level = 'z'